name: Deploy to EC2

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            if [ ! -d "clean-city/.git" ]; then
              rm -rf clean-city
              git clone https://github.com/Ichlasul07/trash-to.git clean-city
            fi

            cd clean-city

            docker build -t cleancity .

            docker stop app || true
            docker rm app || true

            docker run -d -p 3000:3000 --name app cleancity || \
            docker run -d -p 3001:3000 --name app cleancity
